apiVersion: v1
kind: Pod
metadata:
  name: bbtautauvolpod
  labels:
    app: bbtautauvol
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/zichunhao/parcel:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 1Gi
        cpu: "100m"
        ephemeral-storage: 512Gi
      requests:
        memory: 1Gi
        cpu: "100m"
        ephemeral-storage: 512Gi
    volumeMounts:
    - mountPath: /bbtautauvol
      name: bbtautauvol
  restartPolicy: Never
  volumes:
    - name: bbtautauvol
      persistentVolumeClaim:
        claimName: bbtautauvol
