apiVersion: v1
kind: ConfigMap
metadata:
  name: bbtautau-nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;

    load_module "modules/ngx_http_fancyindex_module.so";

    events {
      worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;

      server {
          listen       80;
          server_name  localhost;
          root   /bbtautauvol;

          location / {
            fancyindex on;
            fancyindex_localtime on;
            fancyindex_exact_size off;
            # fancy index theme
            fancyindex_header "/Nginx-Fancyindex-Theme-dark/header.html";
            fancyindex_footer "/Nginx-Fancyindex-Theme-dark/footer.html";
            fancyindex_css_href "/Nginx-Fancyindex-Theme-dark/styles.css";
            # Making sure folder where these files are do not show up in the listing.
            fancyindex_ignore "Nginx-Fancyindex-Theme-dark";
        }
      }
    }
