apiVersion: batch/v1
kind: Job
metadata:
  name: bbtautau-bdt-$job_name
  labels:
    type: bbtautau
spec:
  template:
    spec:
      containers:
      - name: bbtautau
        image: gitlab-registry.nrp-nautilus.io/ludomori99/bbtautau-docker:latest
        command:
          - "/bin/bash"
          - "-c"
          - >
            mkdir -p /bbtautauvol/bdt/$name/ && pip install -e /opt/repo/bbtautau && pip install -e /opt/repo/bbtautau/boostedhh &&
            python /opt/repo/bbtautau/src/bbtautau/postprocessing/bdt.py --years all --train --model $name
            --save-dir /bbtautauvol/bdt/$name --data-path /bbtautauvol/$datapath/ $args
            | tee /bbtautauvol/bdt/$name/log.txt
        volumeMounts:
        - mountPath: /bbtautauvol
          name: bbtautauvol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 32Gi
            cpu: "8"
          requests:
            memory: 32Gi
            cpu: "6"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --recurse-submodules
          - --branch
          - kube
          - https://github.com/LPC-HH/bbtautau.git
          - /opt/repo/bbtautau
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
        resources:
          limits:
            memory: 32Gi
            cpu: "8"
          requests:
            memory: 32Gi
            cpu: "6"
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: bbtautauvol
        persistentVolumeClaim:
          claimName: bbtautauvol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - service-02.nrp.mghpcc.org
      restartPolicy: Never
  backoffLimit: 0
